# git completion from `command line tools`
source /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash

# app completions (from brew)
for FILE in $(brew --prefix)/etc/bash_completion.d/*; do
    if [[ -f "$FILE" && -r "$FILE" ]]; then
        source $FILE
    fi
done

# nvm (from brew)
export NVM_DIR="$HOME/.nvm"
source /usr/local/opt/nvm/nvm.sh

# aliases
source ~/.dotfiles/bash/aliases
