# app completions (from brew)
for FILE in $(brew --prefix)/etc/bash_completion.d/*; do
    if [[ -f "$FILE" && -r "$FILE" ]]; then
        source $FILE
    fi
done

# composer (from brew)
if [ ! -z "$(which composer)" ]; then
    export PATH="$PATH:$HOME/.composer/vendor/bin"
fi

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# nvm (from brew)
export NVM_DIR="$HOME/.nvm"
source /usr/local/opt/nvm/nvm.sh

# aliases
source ~/.dotfiles/bash/aliases
